#!/usr/bin/env bash
# uGC formal verification gate (Frama-C).
#
# Runs two analyses over the formally specified core (ugc/core):
#   1. WP  - deductive proof of the ACSL contracts (with RTE guards);
#      fails unless every goal is discharged.
#   2. Eva - value analysis of formal/eva_main.c driver; fails if any
#      alarm (potential undefined behavior) is reported.
#
# Usage: ./formal/verify.sh
#   FRAMAC=<frama-c binary>  (default: frama-c)
#   WP_TIMEOUT=<seconds per goal>  (default: 60)
#
# Copyright (C) 2026 Demerzel Solutions Limited (Nethermind)
# Author: Maxim Menshikov <maksim.menshikov@nethermind.io>

set -uo pipefail

cd "$(dirname "$0")/.."

FRAMAC="${FRAMAC:-frama-c}"
WP_TIMEOUT="${WP_TIMEOUT:-60}"
NPROC="$(nproc 2>/dev/null || echo 4)"

fail=0

echo "=== WP: deductive verification of ACSL contracts ==="
wp_out=$("$FRAMAC" -wp -wp-rte \
    -wp-timeout "$WP_TIMEOUT" -wp-par "$NPROC" \
    ugc/core/ugc_core.c 2>&1)
wp_status=$?
echo "$wp_out" | grep -E "Proved goals|Qed:|Alt-Ergo|Timeout|Failed|Unknown" \
    | head -20

proved=$(echo "$wp_out" \
    | sed -n 's/.*Proved goals:[[:space:]]*\([0-9][0-9]*\)[[:space:]]*\/[[:space:]]*\([0-9][0-9]*\).*/\1 \2/p')
ok=$(echo "$proved" | awk '{print $1}')
total=$(echo "$proved" | awk '{print $2}')

if [ "$wp_status" -ne 0 ] || [ -z "$ok" ] || [ -z "$total" ] || \
   [ "$ok" != "$total" ] || [ "$total" = "0" ]; then
    echo "WP: FAILED (proved ${ok:-?}/${total:-?} goals)" >&2
    fail=1
else
    echo "WP: OK - all $total goals proved"
fi

echo ""
echo "=== Eva: absence of runtime errors ==="
eva_out=$("$FRAMAC" -eva -eva-precision 2 \
    formal/eva_main.c ugc/core/ugc_core.c ugc/core/ugc_zalloc.c \
    -cpp-extra-args=-Iugc/core 2>&1)
eva_status=$?
echo "$eva_out" | grep -E "alarm|invalid|coverage|Assertions|Preconditions" \
    | head -20

if [ "$eva_status" -ne 0 ] || \
   ! echo "$eva_out" | grep -q "0 alarms generated by the analysis"; then
    echo "Eva: FAILED (alarms or analysis error)" >&2
    fail=1
elif echo "$eva_out" | grep -qE "[1-9][0-9]* invalid"; then
    echo "Eva: FAILED (invalid logical properties)" >&2
    fail=1
else
    echo "Eva: OK - no alarms"
fi

exit $fail
